### ISSUE TITLE
Update contributor list on web site

### ISSUE THREAD

**Issue by mkchandler** [codeforokc/openbudgetokc#106]
Get the most current list of new contributors and add them to the site.

**Comment by mkchandler** [comment]
Alex Ayon
@alex-code4okc

**Comment by mkchandler** [comment]
Peter J. Pih
@railsnewbie257

**Comment by mkchandler** [comment]
James England
@JEinOKC
http://twitter.com/JEinOKC

**Comment by mkchandler** [comment]
Daniel Ashcraft
@dashcraft

**Comment by dashcraft** [comment]
twitter is @d_ofashandfire
I'll submit a pull request if i have time, no biggee.
Thank you for the add!
