### ISSUE TITLE
Get revenue data from city to build cash flow visualization

### ISSUE THREAD

**Issue by mkchandler** [codeforokc/openbudgetokc#11]
In order to visualize cash flow, we need the revenue data in addition to the expense data we already have.

**Comment by mkchandler** [comment]
After a discussion of this at our October meeting, @cahiller will be working with Doug Dowler and the City Budget Office to get this data.

**Comment by cahiller** [comment]
Doug Dowler sent me the correct wording to use for the records request. I submitted one for a CSV file of revenue data and one for 3-digit Agency Numbers and Names. I'll update status here once I receive the data. Doug also made a query that he saved on their server so others can fulfill this request in the future. 
Query name to get Expense: qry_Current_Yr_Budget_detail 
Query name to get Revenue qry_Current_Yr_Budget_Detail_Revenue
