### ISSUE TITLE
Add itemized list below the treemap visualization of what items are visible

### ISSUE THREAD

**Issue by mkchandler** [codeforokc/openbudgetokc#37]
Similar to how Open Budget Oakland displays it on their treemap: http://openbudgetoakland.org/2015-17-proposed-budget-tree.html#fy15-16.expense

**Comment by smurphy8** [comment]
It seems like this might already be done? 
I looked at some of the values to see they were correct and they all seem to be.

**Comment by jagthedrummer** [comment]
Yep, numbers are there and seem correct.

We should right align the number column and sort the table either alphabetically or by value. I think I'd vote for by value.

**Comment by smurphy8** [comment]
#91 addresses the additional requests moved to the other side of the launch as per @mkchandler
