### ISSUE TITLE
Data Visualization Year to Year

### ISSUE THREAD

**Issue by mkchandler** [codeforokc/openbudgetokc#42]
_From @courtlam on February 23, 2016 1:16_

![screen shot 2016-02-22 at 7 12 51 pm](https://cloud.githubusercontent.com/assets/11417361/13238432/8689dc46-d998-11e5-98ac-d1c4716a8969.png)

http://www.visualcinnamon.com/2015/10/different-look-d3-radar-chart.html

_Copied from original issue: codeforokc/okc-budget-data#7_

**Comment by mkchandler** [comment]
_From @mascott on February 23, 2016 2:7_

Thanks!

Just so we remember later, we talked some about trying to group the categories into smaller related sets instead of trying fit all of the data into this graph.

**Comment by smurphy8** [comment]
I think we can call this issue closed and add issues related to the actual radar.
