### ISSUE TITLE
Remove data and representations of data that are non conforming

### ISSUE THREAD

**Issue by smurphy8** [codeforokc/openbudgetokc#47]
Right now in the main branch of the code.  
That is under _src there are data files and trees that are not built the same as the canonical versions that are found in sandbox.  It is something that confused me and I think it was an easy mistake to make.

I would like to clean it up so there is only one "good" data.  I have a couple thoughts about how to do this.
- [ ] Remove old / copy new json files into tree openbudgetokc/_src/data
- [ ] Get rid of 2014-15-budget-tree.jade
- [ ] Replace with zoomable.html (there are some feature differences but we can correct as desired) #46 pt1
- [ ] Make a few writeups in the Readme, perhaps pointing to the wiki on what the canonical data should look like in json form.

Maybe some of this is already planned?  I would be glad to do all these things.

**Comment by cahiller** [comment]
@mascott @mkchandler let me know what y'all think. This sounds good to me

**Comment by smurphy8** [comment]
@cahiller sorry to blow up your inbox but also, is this the right file? 
https://github.com/codeforokc/openbudgetokc/blob/master/sandbox/CODE%20for%20OKC%20FY16%20Final.json
To base features on.

**Comment by cahiller** [comment]
no worries at all! Yes that's the one you want.

**Comment by cahiller** [comment]
[CODE for OKC FY17 Budget.xlsx](https://github.com/codeforokc/openbudgetokc/files/398436/CODE.for.OKC.FY17.Budget.xlsx)

Got 2017 budget data! I didn't want to mess up your flow, so I attached it here instead of merging it in.
