### ISSUE TITLE
TreeMap labels overlapping

### ISSUE THREAD

**Issue by cahiller** [codeforokc/openbudgetokc#49]
Our treemap has labels and utilizes hover. We need to cleanup the boxes where the labels overlap

**Comment by jagthedrummer** [comment]
I'm guessing that this is what we're talking about in this issue?

<img width="305" alt="screen shot 2016-08-22 at 6 37 06 pm" src="https://cloud.githubusercontent.com/assets/58702/17875421/a45ae3da-6897-11e6-9d77-9cbffc17b122.png">

Conceptually what do we want to happen? Something like "if a box is smaller than X by Y then we don't want to display a label at all"?

**Comment by smurphy8** [comment]
Proposed steps:
- [ ] Separate radar js from html
- [ ] Write bounding box violation check code
- [ ] Write tests for code
- [ ] Integrate so that Font size is scaled on violation.

**Comment by smurphy8** [comment]
https://github.com/codeforokc/openbudgetokc/pull/90

I think that fixes this!  I vote close!
