### ISSUE TITLE
c4OKC_2017.csv Reflects Adopted 2016 Budget Not Proposed 2017

### ISSUE THREAD

**Issue by railsnewbie257** [codeforokc/openbudgetokc#57]
Checking the _src/data/fy2017/c4okc_fy2017.csv the Agency columns for 

"Airport" pg C-11 (page #  in 2017 Proposed Budget book)
"General Fund" pg B-15
"Debt Servicing" pg E-98

 match the column for "Adopted FY16" as opposed to "Proposed FY17" in the budget books.

Also fy2016 and fy2017 expense spreadsheets appear to be the same.

We should try to get the "Proposed 2017" spreadsheet as quickly as possible before it changes due to budget modifications.

[Budget and Tax Report webpage](https://www.okc.gov/departments/finance/financial-and-budget-reports/budget-and-tax-reports)

[2017 Proposed Budget](https://www.okc.gov/home/showdocument?id=4682)

@cahiller: Please have a look and ask Doug for the 2017 Proposed Budget spreadsheet

**Comment by smurphy8** [comment]
probably we should reflect adopted and proposed in the file name convention as well as expense revenue?

**Comment by cahiller** [comment]
@railsnewbie257 i'll take a look at the data and get with Doug about it

**Comment by railsnewbie257** [comment]
@cahiller Any luck with Doug?  What we need is the spreadsheet that matches the Proposed 2017 numbers in the budget book.  I'm worried that there may be changes made to the budget database and  Doug had said that updates occur all the time and it's difficult to roll back.

**Comment by mkchandler** [comment]
This is fixed in #61 and #62
