### ISSUE TITLE
How is the radar chart working?

### ISSUE THREAD

**Issue by jagthedrummer** [codeforokc/openbudgetokc#58]
As near as we can tell the data we have for 2016 and 2017 are identical, but we're getting different results on the radar chart. Either those data files aren't identical and we need to figure out how to tell the difference between them OR we're somehow parsing identical data into two different "shapes".

**Comment by smurphy8** [comment]
@jagthedrummer  yeah no they are identical... 
![doubled_up](https://cloud.githubusercontent.com/assets/182668/17877253/5b77de88-68a7-11e6-8363-a5eba8c06633.png)

**Comment by smurphy8** [comment]
When I fixed the axis problem it fixed this.

**Comment by smurphy8** [comment]
I feel very uncertain about the whole way the axis system is working in radar chart.  I don't think it is actually selecting the axis appropriately.  I am investigating now.

**Comment by smurphy8** [comment]
Yeah, so the radarChart feature is just pulling its axis from the first series range instead of looking across all data fields.  So I need to do something to make the chart more sophisticated.

**Comment by jagthedrummer** [comment]
Cool, I'm glad we at least know what's going on. We figured out right at the end that they were likely the same numbers, just in a different order. It looks like we don't actually have 2017 data, so we're going to trace the line backwards and see where things went funky.

@cahiller would you mind attaching the actual Excel file that you got from Doug for 2017?

**Comment by jagthedrummer** [comment]
Oops. Didn't mean to close that.

**Comment by mkchandler** [comment]
We received the actual 2017 data in #61 and #62. @smurphy8 is now continuing work on the radar.

**Comment by smurphy8** [comment]
This issue is closely related to #53.  I submitted a PR that fixes it.

**Comment by smurphy8** [comment]
@mkchandler @jagthedrummer The PR for this was accepted yesterday, this can probably be closed.
