### ISSUE TITLE
Add description and instructions to Budget Tree page

### ISSUE THREAD

**Issue by mkchandler** [codeforokc/openbudgetokc#67]
In addition to the table that is being added in #64 (table), we should try to follow the format of Oakland for displaying the treemap page: http://openbudgetoakland.org/2016-17-adjusted-budget-tree.html#fy16-17.expense

**Comment by mathewmorris** [comment]
Proposed description from Nov. 9 Online Hack Night for tree map

Select year and account (revenues or expenses). Click on a fund to see the departments that receive its funding. Click on that department to see its spending or revenue. To step out of the department, click ‘Budget’ until you reach the desired department.
