### ISSUE TITLE
Combine feedback.html and contact.html and update text

### ISSUE THREAD

**Issue by mkchandler** [codeforokc/openbudgetokc#70]
There is no need to have 2 pages for contacting us. We should update it to have a lot of the info currently in `feedback.html` but with links to our Issues page in the repo as well as our e-mail address and twitter account.

**Comment by mathewmorris** [comment]
So we want to just have the feedback page? Or Contact Us? I made a pull request that pulled everything into the Contact Us page and fixed/added links. I didn't put a link to our issues page, but that won't be hard to add.
