### ISSUE TITLE
Add description and rename budget radar

### ISSUE THREAD

**Issue by mkchandler** [codeforokc/openbudgetokc#71]
We need to add a description of how the budget radar is working as well as change the name to something along the lines of "Budget Changes".

We are open to ideas for naming this visualization.

**Comment by mathewmorris** [comment]
We could name it something like "Budget Evolution" and basically describe how it shows the evolution of the budget over the years. We only have data for this year and next but over time it will show how the budget has evolved instead of changed. I feel like evolution is a better word simply because it refers to the adaptation of the budget.

**Comment by thirdcreed** [comment]
Budget Evolution Radar

The radar shows, at a glance, the shape of the budget allocation for each fiscal year.  The further out on the radar the greater percentage of the budget allocated.  Hover over the small filled in circles to see the exact percentage allocated.

Is this the kind of content we want there? Are we simply trying to describe how to use the tool?

**Comment by mathewmorris** [comment]
Proposed description from Nov 9 Online Hack Night for radar.

## Budget Evolution

The radar shows the shape of the budget allocation for each fiscal year. The further out on the radar the greater percentage of the budget allocated. Hover over the small filled in circles to see the exact percentage allocated.

**Comment by mkchandler** [comment]
Should we highlight that it is comparing 2 different years next to each other?

**Comment by mathewmorris** [comment]
ah yes. That would be nice. Are we going to have the potential of more than two years?

**Comment by mkchandler** [comment]
We could compare more than two, but don't have any plans for that at the moment.

**Comment by jagthedrummer** [comment]
We should also change `fy2016` to `FY2016` (for all years).

**Comment by jagthedrummer** [comment]
Slightly modified text from @mathewmorris. Let's get this into a PR.

--- 

# Budget Evolution

This graph shows the shape of the budget allocation for each fiscal year. The further out on the graph the greater percentage of the budget allocated. Hover over the small filled in circles to see the exact percentage allocated.
