### ISSUE TITLE
Some visual tweaks needed to be fixed on landing page

### ISSUE THREAD

**Issue by mathewmorris** [codeforokc/openbudgetokc#81]
Probably having to do with the crazy way Jade (or pug) does spaces after the pipes. 

Just need to go through and add spaces around the emphasized links.

![image](https://cloud.githubusercontent.com/assets/10860014/20164623/7204b808-a6cb-11e6-8525-f4f79cb9c50d.png)

**Comment by mkchandler** [comment]
@mathewmorris I took at stab at this and am about to open the pull request
